### ISSUE TITLE
vyos_facts not working with ansible==2.10

### ISSUE THREAD

**Issue by np422** [ansible-collections/vyos.vyos#109]
##### SUMMARY

Using vyos_facts does not work when using ansible==2.10

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vyos_facts

##### ANSIBLE VERSION

```paste below

```

##### CONFIGURATION

```
ansible-config dump --only-changed
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/ops/.secret

ansible --version
ansible 2.10.3
  config file = None
  configured module search path = ['/home/ops/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ops/test/venv-2.10/lib/python3.6/site-packages/ansible
  executable location = /home/ops/test/venv-2.10/bin/ansible
  python version = 3.6.9 (default, Oct  8 2020, 12:12:24) [GCC 8.4.0]

```

##### OS / ENVIRONMENT

Host running ansible commands: Ubuntu 18.04.5 LTS

Vyos firewall:

```
Version:          VyOS 1.2.3
Built by:         Sentrium S.L.
Built on:         Thu 19 Sep 2019 21:09 UTC
Build UUID:       0fec8d46-3f04-41b0-b856-0695a2f50015
Build Commit ID:  24f1a74bc88f3a

Architecture:     x86_64
Boot via:         installed image
System type:      KVM guest

Hardware vendor:  Virtuozzo
Hardware model:   OpenStack Compute
Hardware S/N:     988eec22-2940-4d83-8b76-6b2418e64146
Hardware UUID:    988eec22-2940-4d83-8b76-6b2418e64146

Copyright:        VyOS maintainers and contributors
```

##### STEPS TO REPRODUCE

Inventory:
```yaml
[vyos]
hel-fw-01              ansible_host=172.16.21.75

[vyos:vars]
ansible_user=vyos
ansible_connection=network_cli
ansible_network_os=vyos
```
Playbook:
```yaml
- name: Firwall configuration, rules and aliases only
  hosts:
    - hel-fw-01
  gather_facts: true
  tasks:
    - name: Get running config from remote firewall
      vyos_facts:
        gather_subset: all
        gather_network_resources: all
      register: orig_vyos_config
```

Commands to reproduce:
```
python3 -m venv venv-2.10
python3 -m venv venv-2.9
. ./venv-2.9/bin/activate
pip install ansible==2.9 paramiko
ansible-playbook -i inventory test.yml
# NOTE: Succesful, see output below
. ./venv-2.10/bin/activate
pip install ansible==2.10 paramiko
ansible-playbook -i inventory test.yml
# Note: Failure, see output below
```
##### EXPECTED RESULTS

```
TASK [Get running config from remote firewall] *********************************************************************************************************************************
[WARNING]: default value for `gather_subset` will be changed to `min` from `!config` v2.11 onwards

ok: [hel-fw-01]
```

##### ACTUAL RESULTS
Verbose output using `-v -v -v`
```
TASK [Get running config from remote firewall] *********************************************************************************************************************************
task path: /home/ops/test/test.yml:6
redirecting (type: connection) ansible.builtin.network_cli to ansible.netcommon.network_cli
redirecting (type: terminal) ansible.builtin.vyos to vyos.vyos.vyos
redirecting (type: cliconf) ansible.builtin.vyos to vyos.vyos.vyos
redirecting (type: action) ansible.builtin.vyos to vyos.vyos.vyos
redirecting (type: action) ansible.builtin.vyos to vyos.vyos.vyos
<172.16.21.75> ESTABLISH LOCAL CONNECTION FOR USER: ops
<172.16.21.75> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ops/.ansible/tmp/ansible-local-17007nwxg3giw `"&& mkdir "` echo /home/ops/.ansible/tmp/ansible-local-17007nwxg3giw/ansible-tmp-1606504658.6681817-17052-1823495894419 `" && echo ansible-tmp-1606504658.6681817-17052-1823495894419="` echo /home/ops/.ansible/tmp/ansible-local-17007nwxg3giw/ansible-tmp-1606504658.6681817-17052-1823495894419 `" ) && sleep 0'
redirecting (type: modules) ansible.builtin.vyos_facts to vyos.vyos.vyos_facts
Using module file /home/ops/.ansible/collections/ansible_collections/vyos/vyos/plugins/modules/vyos_facts.py
<172.16.21.75> PUT /home/ops/.ansible/tmp/ansible-local-17007nwxg3giw/tmpgafjez1p TO /home/ops/.ansible/tmp/ansible-local-17007nwxg3giw/ansible-tmp-1606504658.6681817-17052-1823495894419/AnsiballZ_vyos_facts.py
<172.16.21.75> EXEC /bin/sh -c 'chmod u+x /home/ops/.ansible/tmp/ansible-local-17007nwxg3giw/ansible-tmp-1606504658.6681817-17052-1823495894419/ /home/ops/.ansible/tmp/ansible-local-17007nwxg3giw/ansible-tmp-1606504658.6681817-17052-1823495894419/AnsiballZ_vyos_facts.py && sleep 0'
<172.16.21.75> EXEC /bin/sh -c '/usr/bin/python /home/ops/.ansible/tmp/ansible-local-17007nwxg3giw/ansible-tmp-1606504658.6681817-17052-1823495894419/AnsiballZ_vyos_facts.py && sleep 0'
<172.16.21.75> EXEC /bin/sh -c 'rm -f -r /home/ops/.ansible/tmp/ansible-local-17007nwxg3giw/ansible-tmp-1606504658.6681817-17052-1823495894419/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/home/ops/.ansible/tmp/ansible-local-17007nwxg3giw/ansible-tmp-1606504658.6681817-17052-1823495894419/AnsiballZ_vyos_facts.py", line 102, in <module>
    _ansiballz_main()
  File "/home/ops/.ansible/tmp/ansible-local-17007nwxg3giw/ansible-tmp-1606504658.6681817-17052-1823495894419/AnsiballZ_vyos_facts.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/ops/.ansible/tmp/ansible-local-17007nwxg3giw/ansible-tmp-1606504658.6681817-17052-1823495894419/AnsiballZ_vyos_facts.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.vyos.vyos.plugins.modules.vyos_facts', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python2.7/runpy.py", line 188, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_vyos_facts_payload_Ue7uxh/ansible_vyos_facts_payload.zip/ansible_collections/vyos/vyos/plugins/modules/vyos_facts.py", line 177, in <module>
  File "/tmp/ansible_vyos_facts_payload_Ue7uxh/ansible_vyos_facts_payload.zip/ansible_collections/vyos/vyos/plugins/modules/vyos_facts.py", line 168, in main
  File "/tmp/ansible_vyos_facts_payload_Ue7uxh/ansible_vyos_facts_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/facts/facts.py", line 97, in get_facts
  File "/tmp/ansible_vyos_facts_payload_Ue7uxh/ansible_vyos_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 131, in get_network_resources_facts
  File "/tmp/ansible_vyos_facts_payload_Ue7uxh/ansible_vyos_facts_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/facts/ospf_interfaces/ospf_interfaces.py", line 81, in populate_facts
  File "/tmp/ansible_vyos_facts_payload_Ue7uxh/ansible_vyos_facts_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/rm_templates/ospf_interfaces.py", line 308, in __init__
  File "/tmp/ansible_vyos_facts_payload_Ue7uxh/ansible_vyos_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/network_template.py", line 22, in __init__
  File "/tmp/ansible_vyos_facts_payload_Ue7uxh/ansible_vyos_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/utils.py", line 726, in __init__
ImportError: jinja2 is required but does not appear to be installed.  It can be installed using `pip install jinja2`
fatal: [hel-fw-01]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/ops/.ansible/tmp/ansible-local-17007nwxg3giw/ansible-tmp-1606504658.6681817-17052-1823495894419/AnsiballZ_vyos_facts.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/ops/.ansible/tmp/ansible-local-17007nwxg3giw/ansible-tmp-1606504658.6681817-17052-1823495894419/AnsiballZ_vyos_facts.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/ops/.ansible/tmp/ansible-local-17007nwxg3giw/ansible-tmp-1606504658.6681817-17052-1823495894419/AnsiballZ_vyos_facts.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.vyos.vyos.plugins.modules.vyos_facts', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python2.7/runpy.py\", line 188, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_vyos_facts_payload_Ue7uxh/ansible_vyos_facts_payload.zip/ansible_collections/vyos/vyos/plugins/modules/vyos_facts.py\", line 177, in <module>\n  File \"/tmp/ansible_vyos_facts_payload_Ue7uxh/ansible_vyos_facts_payload.zip/ansible_collections/vyos/vyos/plugins/modules/vyos_facts.py\", line 168, in main\n  File \"/tmp/ansible_vyos_facts_payload_Ue7uxh/ansible_vyos_facts_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/facts/facts.py\", line 97, in get_facts\n  File \"/tmp/ansible_vyos_facts_payload_Ue7uxh/ansible_vyos_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py\", line 131, in get_network_resources_facts\n  File \"/tmp/ansible_vyos_facts_payload_Ue7uxh/ansible_vyos_facts_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/facts/ospf_interfaces/ospf_interfaces.py\", line 81, in populate_facts\n  File \"/tmp/ansible_vyos_facts_payload_Ue7uxh/ansible_vyos_facts_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/rm_templates/ospf_interfaces.py\", line 308, in __init__\n  File \"/tmp/ansible_vyos_facts_payload_Ue7uxh/ansible_vyos_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/network_template.py\", line 22, in __init__\n  File \"/tmp/ansible_vyos_facts_payload_Ue7uxh/ansible_vyos_facts_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/utils.py\", line 726, in __init__\nImportError: jinja2 is required but does not appear to be installed.  It can be installed using `pip install jinja2`\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

**Comment by GomathiselviS** [comment]
@np422 Please check if jinja2 is installed and the value of ansible_python_interpreter is python.

**Comment by np422** [comment]
The python_interpreter used was /usr/bin/python.

Jinja2 was only installed in the two venv's I created and not using the system `/usr/bin/pip2 install`

Either installing Jinja2 globally using pip2 or setting `ansible_python_interpreter=/home/ops/test/venv-2.10/bin/python` in the inventory group_vars section solved the issue.

Thank you for pointing me in the correct direction.
