### ISSUE TITLE
KeyError on 'enabled' when attempting to configure interface not already represented in config

### ISSUE THREAD

**Issue by mhuxtable** [ansible-collections/vyos.vyos#91]
##### SUMMARY
I brought up a clean VyOS host and attempted to configure one of its interfaces, `eth1`. `eth1` did not have any pre-existing configuration in the on-disk config and was disabled. When attempting to run the playbook described below, rather than enabling the interface, the ansible runner failed with error `KeyError: 'enabled'`. It appears the `vyos_interfaces` module assumes it will always have an `enabled` key in some configuration sections and does not handle the error raised when this key does not exist.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

vyos.vyos.vyos_interfaces

##### ANSIBLE VERSION

```paste below
ansible 2.9.10
  config file = None
  configured module search path = ['/Users/matt/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.10/libexec/lib/python3.8/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.3 (default, May 27 2020, 20:54:22) [Clang 11.0.3 (clang-1103.0.32.59)]
```

##### CONFIGURATION

```paste below
[nil output]
```

##### OS / ENVIRONMENT

VyOS 1.2.5

##### STEPS TO REPRODUCE

1. Bring up a new VyOS host which does not have any configuration sections for at least one interface
1. Run the playbook below, substituting the NIC identity which has no configuration for `eth1` as appropriate

```yaml
- name: configure physical interfaces
  block:
    - name: ensure L2 configuration is applied to physical interfaces
      vyos.vyos.vyos_interfaces:
        config:
          - name: eth1
            description: Configured by Ansible.
            enabled: yes
            duplex: auto
            speed: auto
            vifs: []
        state: replaced
```

##### EXPECTED RESULTS

The interface `eth1` is brought up with the configuration provided. The run completes without errors.

##### ACTUAL RESULTS

The following exception was raised:

```paste below
The full traceback is:
Traceback (most recent call last):
  File "/Users/matt/.ansible/tmp/ansible-local-228616bbu14rn/ansible-tmp-1602007357.662739-22962-83805022306893/AnsiballZ_vyos_interfaces.py", line 102, in <module>
    _ansiballz_main()
  File "/Users/matt/.ansible/tmp/ansible-local-228616bbu14rn/ansible-tmp-1602007357.662739-22962-83805022306893/AnsiballZ_vyos_interfaces.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/Users/matt/.ansible/tmp/ansible-local-228616bbu14rn/ansible-tmp-1602007357.662739-22962-83805022306893/AnsiballZ_vyos_interfaces.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.vyos.vyos.plugins.modules.vyos_interfaces', init_globals=None, run_name='__main__', alter_sys=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 188, in run_module
    fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/var/folders/1_/7ll3cry521v04hn7pwt_k6l00000gn/T/ansible_vyos.vyos.vyos_interfaces_payload_9zMTVo/ansible_vyos.vyos.vyos_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/modules/vyos_interfaces.py", line 1134, in <module>
  File "/var/folders/1_/7ll3cry521v04hn7pwt_k6l00000gn/T/ansible_vyos.vyos.vyos_interfaces_payload_9zMTVo/ansible_vyos.vyos.vyos_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/modules/vyos_interfaces.py", line 1129, in main
  File "/var/folders/1_/7ll3cry521v04hn7pwt_k6l00000gn/T/ansible_vyos.vyos.vyos_interfaces_payload_9zMTVo/ansible_vyos.vyos.vyos_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/config/interfaces/interfaces.py", line 80, in execute_module
  File "/var/folders/1_/7ll3cry521v04hn7pwt_k6l00000gn/T/ansible_vyos.vyos.vyos_interfaces_payload_9zMTVo/ansible_vyos.vyos.vyos_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/config/interfaces/interfaces.py", line 124, in set_config
  File "/var/folders/1_/7ll3cry521v04hn7pwt_k6l00000gn/T/ansible_vyos.vyos.vyos_interfaces_payload_9zMTVo/ansible_vyos.vyos.vyos_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/config/interfaces/interfaces.py", line 173, in set_state
  File "/var/folders/1_/7ll3cry521v04hn7pwt_k6l00000gn/T/ansible_vyos.vyos.vyos_interfaces_payload_9zMTVo/ansible_vyos.vyos.vyos_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/config/interfaces/interfaces.py", line 186, in _state_replaced
  File "/var/folders/1_/7ll3cry521v04hn7pwt_k6l00000gn/T/ansible_vyos.vyos.vyos_interfaces_payload_9zMTVo/ansible_vyos.vyos.vyos_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/config/interfaces/interfaces.py", line 286, in _state_deleted
KeyError: 'enabled'
fatal: [vyos-0]: FAILED! => changed=false
  module_stderr: |-
    Traceback (most recent call last):
      File "/Users/matt/.ansible/tmp/ansible-local-228616bbu14rn/ansible-tmp-1602007357.662739-22962-83805022306893/AnsiballZ_vyos_interfaces.py", line 102, in <module>
        _ansiballz_main()
      File "/Users/matt/.ansible/tmp/ansible-local-228616bbu14rn/ansible-tmp-1602007357.662739-22962-83805022306893/AnsiballZ_vyos_interfaces.py", line 94, in _ansiballz_main
        invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
      File "/Users/matt/.ansible/tmp/ansible-local-228616bbu14rn/ansible-tmp-1602007357.662739-22962-83805022306893/AnsiballZ_vyos_interfaces.py", line 40, in invoke_module
        runpy.run_module(mod_name='ansible_collections.vyos.vyos.plugins.modules.vyos_interfaces', init_globals=None, run_name='__main__', alter_sys=True)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 188, in run_module
        fname, loader, pkg_name)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 82, in _run_module_code
        mod_name, mod_fname, mod_loader, pkg_name)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
        exec code in run_globals
      File "/var/folders/1_/7ll3cry521v04hn7pwt_k6l00000gn/T/ansible_vyos.vyos.vyos_interfaces_payload_9zMTVo/ansible_vyos.vyos.vyos_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/modules/vyos_interfaces.py", line 1134, in <module>
      File "/var/folders/1_/7ll3cry521v04hn7pwt_k6l00000gn/T/ansible_vyos.vyos.vyos_interfaces_payload_9zMTVo/ansible_vyos.vyos.vyos_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/modules/vyos_interfaces.py", line 1129, in main
      File "/var/folders/1_/7ll3cry521v04hn7pwt_k6l00000gn/T/ansible_vyos.vyos.vyos_interfaces_payload_9zMTVo/ansible_vyos.vyos.vyos_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/config/interfaces/interfaces.py", line 80, in execute_module
      File "/var/folders/1_/7ll3cry521v04hn7pwt_k6l00000gn/T/ansible_vyos.vyos.vyos_interfaces_payload_9zMTVo/ansible_vyos.vyos.vyos_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/config/interfaces/interfaces.py", line 124, in set_config
      File "/var/folders/1_/7ll3cry521v04hn7pwt_k6l00000gn/T/ansible_vyos.vyos.vyos_interfaces_payload_9zMTVo/ansible_vyos.vyos.vyos_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/config/interfaces/interfaces.py", line 173, in set_state
      File "/var/folders/1_/7ll3cry521v04hn7pwt_k6l00000gn/T/ansible_vyos.vyos.vyos_interfaces_payload_9zMTVo/ansible_vyos.vyos.vyos_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/config/interfaces/interfaces.py", line 186, in _state_replaced
      File "/var/folders/1_/7ll3cry521v04hn7pwt_k6l00000gn/T/ansible_vyos.vyos.vyos_interfaces_payload_9zMTVo/ansible_vyos.vyos.vyos_interfaces_payload.zip/ansible_collections/vyos/vyos/plugins/module_utils/network/vyos/config/interfaces/interfaces.py", line 286, in _state_deleted
    KeyError: 'enabled'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1

```

The VyOS config has no configuration committed for `eth1`:

```
$ show configuration commands | grep inter
set interfaces ethernet eth0 address 'dhcp'
set interfaces ethernet eth0 duplex 'auto'
set interfaces ethernet eth0 speed 'auto'
set interfaces loopback lo
```

**Comment by mhuxtable** [comment]
A workaround for this issue is explicitly adding a configuration section with imperative config management in the step before attempting to configure it:

```yaml
- name: ensure interfaces are enabled
  vyos.vyos.vyos_config:
    lines:
      - set interfaces ethernet eth1
    save: yes
```
